### ISSUE TITLE
解决办法 兄弟们 

### ISSUE THREAD

**Issue by objectxhg** [x-ream/sqli#6]
兄弟们找到问题了 你们去github上面找到这个项目：x-ream/sqli
把那个Watch 改一下就好了 哈哈笑死我了
![image](https://user-images.githubusercontent.com/38096419/95950054-763a2400-0e26-11eb-8e6a-03aa187a44c1.png)

**Comment by sim-wangyan** [comment]
是的，我也收到了很多邮件，应该是github设计上的问题，点Unwatch就可以了
