### ISSUE TITLE
DaoHelper Rename As SqlBuilder

### ISSUE THREAD

**Issue by sim-wangyan** [x-ream/sqli#9]
DaoHelper can not describe the logical, it is SqlBuilder

**Comment by NextFeng** [comment]
又开始了么发自我的华为手机-------- 原始邮件 --------发件人： Sim Wang <notifications@github.com>日期： 2020年10月15日周四 16:06收件人： x-ream/sqli <sqli@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： Re: [x-ream/sqli] DaoHelper Rename As SqlBuilder (#9)
Closed #9.
